//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowaMig.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agence
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public int ZoneId { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
